---
abstract: 'Perl Performance Benchmark Suite'
author:
  - 'Steffen Schwigon, C<< <ss5 at renormalist.net> >>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Formance
no_index:
  directory:
    - inc
    - t
requires:
  Data::YAML::Writer: 0
  Mail::SpamAssassin: 0
  Net::DNS: 0
  Net::IP: 0
  Perl::Formance::Cargo: 0
  Regexp::Common: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
